---
- hosts: localhost
  gather_facts: false

  vars:
    registry_image: registry:2

  tasks:
    - name: Ensure the docker registry imaage is present
      docker_image:
        name: "{{ registry_image }}"
        source: pull

    - name: Run the docker registry container
      docker_container:
        name: registry
        image: "{{ registry_image }}"
        state: started
        published_ports:
          - 5000:5000

  