# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu2004"
  config.ssh.insert_key = false
  # config.vm.synced_folder "src/", "/srv/website"
  
  # General VirtualBox VM configuration.
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
    v.linked_clone = true
  end

  # Metrics server instance.
  config.vm.define "metrics" do |metrics|
    metrics.vm.hostname = "metrics.lab"
    metrics.vm.network :private_network, ip: "192.168.10.2"
  end

  # Web instance.
  config.vm.define "web" do |web|
    web.vm.hostname = "web.lab"
    web.vm.network :private_network, ip: "192.168.10.3"
  end
end