---
- hosts: k8s-master
  become: true

  pre_tasks:
    - name: Ensure pip is installed.
      package:
        name: python-pip
        state: present

    - name: Ensure Openshift client is installed
      pip:
        name: openshift
        state: present

  tasks:
    - name: Apply definition file from ansible
      k8s:
        state: present
        definition: "{{ lookup('file', 'files/nginx.yml') | from_yaml }\
          }"

    - name: Expose nginx service with inline service definition
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app: nginx
            name: a4d-nginx
            namespace: default
          spec:
            type: NodePort
            ports:
              - port: 80
                protocol: TCP
                targetPort: 80
            selector:
              app: nginx

    - name: Get details of a4d-nginx service
      k8s_info:
        api_version: v1
        kind: Service
        name: a4d-nginx
        namespace: default
      register: a4d_nginx_service

    - name: Print the NodePort of the service
      debug:
        var: a4d_nginx_service.resources[0].spec.ports[0].nodePort
