---
- hosts: k8s-master
  become: yes

  tasks:
    - name: Remove resources in nginx deployment
      k8s:
        state: absent
        definition: "{{ lookup('file', 'files/nginx.yml') | from_yaml }\
          }"

    - name: Remove the nginx service
      k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: default
        name: a4d-nginx
