---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Pull the postgres docker image
      docker_image:
        name: "postgres:{{ postgres_version }}"
        source: pull

    - name: Pull the Odoo docker image
      docker_image:
        name: "odoo:{{ odoo_version }}"
        source: pull

    - name: Start postgres server
      docker_container:
        name: db
        detach: yes
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres

    - name: Start the Odoo server
      docker_container:
        name: "{{ container_name }}"
        image: "odoo:{{ odoo_version }}"
        volumes: "{{ addons_dir }}:/mnt/extra-addons"
        state: started
        published_ports:
          - "{{ published_ports }}"
        links:
          - "db:db"
