---
- hosts: localhost
  gather_facts: false

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: hello-go
    replicas: 1
    app_state: absent

  pre_tasks:
  - name: Check Minikube's status.
    command: minikube status
    register: minikube_status
    changed_when: false
    ignore_errors: true

  - name: Start Minikube if it's not running.
    command: minikube start
    when: "not minikube_status.stdout or 'Running' not in minikube_status.stdout"

  tasks:
    - name: Get exisiting image hash
      shell: |
        eval $(minikube docker-env)
        docker images -q {{ image_name }}
      register: image_hash
      changed_when: false

    - name: Build image if not present
      shell: |
        eval $(minikube docker-env)
        docker build -t {{ image_name }} ../hello-go
      when: not image_hash.stdout

    - name: Create deployment for hello-go
      k8s:
        state: "{{ app_state }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: hello-go
            namespace: default
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: hello-go
            template:
              metadata:
                labels:
                  app: hello-go
              spec:
                containers:
                - name: hello-go
                  image: "{{ image_name }}"
                  imagePullPolicy: IfNotPresent
                  ports:
                  - containerPort: 8180
    
    - name: Create service for hello-go
      k8s:
        state: "{{ app_state }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: hello-go
            namespace: default
          spec:
            type: LoadBalancer
            selector:
              app: hello-go
            ports:
            - port: 8180
              targetPort: 8180
          
  post_tasks:
    - name: Expose hello-go on minikube
      command: minikube service hello-go --url=true
      changed_when: false
      register: minikube_service
    
    - debug:
        msg: "Hello Go URL: {{ minikube_service['stdout_lines'][0] }}"
